sourcedir: D:/js/extjs-4.1.2-commercial
version: 4.1.2
groupId: resources
baseartifactId: extjs
destdir: ./test
files:
  bootstrap.js : src
  ext-all-debug-w-comments.js : core
  ext-all-debug.js : core
  ext-all-dev.js : core
  ext-all.js : core
  ext-debug-w-comments.js : src
  ext-debug.js : src
  ext-dev.js : src
  ext-neptune-debug-w-comments.js : theme-neptune
  ext-neptune-debug.js : theme-neptune
  ext-neptune.js : theme-neptune
  ext.js : src
  locale : core
  src : src
  resources/css/ext-all-access-debug.css : theme-access
  resources/css/ext-all-access.css : theme-access
  resources/css/ext-all-debug.css : theme-default
  resources/css/ext-all-gray-debug.css : theme-gray
  resources/css/ext-all-gray.css : theme-gray
  resources/css/ext-all.css : theme-default
  resources/css/ext-neptune-debug.css : theme-neptune
  resources/css/ext-neptune.css : theme-neptune
  resources/themes/images/access : theme-access
  resources/themes/images/default : theme-default
  resources/themes/images/gray : theme-gray
  resources/themes/images/neptune : theme-neptune
  examples/ux : ux
mappings:
  examples/ux : ux  
